observation_column_mapping = {
    'ID': 'sequentialId',
    'LocalID': 'localId',
    'Date': 'date',
    'Time': 'timeSpecifier',
    'Report type': 'observationMethod',
    'Country': 'country',
    'Site': 'site',
    'Location': 'site',
    'Latitude': 'latitude',
    'Lat': 'latitude',
    'Longitude': 'longitude',
    'Long': 'longitude',
    'Depth': 'depth',
    'Distance': 'distance',
    'Temperature': 'temperature',
    'Temp': 'temperature',
    'Substrate': 'substrate',
    'SurveyMethod': 'surveyMethod',
    'Method': 'surveyMethod',
    'Count': 'count',
    'Number': 'count',
    'Stage': 'stage',
    'LifeStage': 'stage',
    'Sex': 'sex',
    'Gender': 'sex',
    'Condition': 'condition',
    'Species': 'species',
    'SpeciesName': 'species',
    'Length': 'length',
    'DiskLength': 'diskLength',
    'Width': 'width',
    'Weight': 'weight',
    'Group': 'group',
    'Reporter': 'reporter',
    'Observer': 'reporter',
    'Photographer': 'photographer',
    'UserEmail': 'byUser',
    'MediaSource': 'mediaSource',
    'Description': 'description',
    'Comments': 'comments',
    'Notes': 'comments',
    'Links': 'urlLinks',
}

enum_mapping = {


}